# kind: pipeline
# type: docker
# name: docker-build

# steps:
#   - name: build-and-push
#     image: plugins/docker
#     settings:
#       repo: mb2214/dronexdocker
#       tags: latest
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password



kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      repo: yourdockerhubusername/drone-node-app
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy-to-ec2
    image: appleboy/ssh-action
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      script:
        - cd ~/drone-deploy
        - docker compose down
        - docker compose pull
        - docker compose up -d
