version: '3'
services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - 8000:80
    volumes:
      - ./drone:/data
    restart: always

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always